"""initial content schema

Revision ID: 529bfb7e2e57
Revises:
Create Date: 2026-10-05 15:03:12.986682

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "529bfb7e2e57"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concepts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("concept_key", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("content_status", sa.String(length=20), nullable=False),
        sa.Column("generation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("generation_error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "content_status IN ('not_generated', 'generating', 'ready', 'failed')",
            name="content_status_valid",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("concept_key"),
    )
    op.create_table(
        "curricula",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("requested_topic", sa.String(length=200), nullable=False),
        sa.Column("generation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("concept_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("facet", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("key_takeaway", sa.Text(), nullable=False),
        sa.Column("visual", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("quick_check", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("concept_id", "position", name="uq_card_concept_position"),
    )
    op.create_index(op.f("ix_cards_concept_id"), "cards", ["concept_id"], unique=False)
    op.create_table(
        "curriculum_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("curriculum_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.ForeignKeyConstraint(["curriculum_id"], ["curricula.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["curriculum_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_curriculum_nodes_concept_id"), "curriculum_nodes", ["concept_id"], unique=False)
    op.create_index(
        op.f("ix_curriculum_nodes_curriculum_id"), "curriculum_nodes", ["curriculum_id"], unique=False
    )
    op.create_index(op.f("ix_curriculum_nodes_parent_id"), "curriculum_nodes", ["parent_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_curriculum_nodes_parent_id"), table_name="curriculum_nodes")
    op.drop_index(op.f("ix_curriculum_nodes_curriculum_id"), table_name="curriculum_nodes")
    op.drop_index(op.f("ix_curriculum_nodes_concept_id"), table_name="curriculum_nodes")
    op.drop_table("curriculum_nodes")
    op.drop_index(op.f("ix_cards_concept_id"), table_name="cards")
    op.drop_table("cards")
    op.drop_table("curricula")
    op.drop_table("concepts")
    # ### end Alembic commands ###
